steps:
  - id: build-backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform=linux/amd64
      - -t
      - asia-south1-docker.pkg.dev/arcane-firefly-465906-h7/lead-gen/backend:$COMMIT_SHA
      - -t
      - asia-south1-docker.pkg.dev/arcane-firefly-465906-h7/lead-gen/backend:latest
      - ./backend

  - id: push-backend
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - asia-south1-docker.pkg.dev/arcane-firefly-465906-h7/lead-gen/backend
    waitFor: [build-backend]

  - id: deploy-backend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - lead-gen-backend
      - --image=asia-south1-docker.pkg.dev/arcane-firefly-465906-h7/lead-gen/backend:$COMMIT_SHA
      - --region=asia-south1
      - --allow-unauthenticated
      - --set-env-vars=SPREADSHEET_ID=1UVcBZgaDsrcZuTEEVS5rX9KSP7FY4wNte7_CwS7FHWQ,SERVICE_ACCOUNT_PATH=/secrets/service-account.json,FRONTEND_URL=$_FRONTEND_URL
      - --set-secrets=/secrets/service-account.json=lead-gen-sa:latest
    waitFor: [push-backend]

substitutions:
  _FRONTEND_URL: https://lead-generation-mu-beige.vercel.app

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
